import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {extractText,conflicts,ownershipPaths,matchEntities,features,escapeHtml} from '../dist/core.js';
import {CASES,SAMPLE} from '../dist/data.js';
const model=JSON.parse(readFileSync(new URL('../dist/model.json',import.meta.url)));
const parsed=text=>extractText(text,'Northstar Commerce PLC','doc').relations.map((r,i)=>({...r,id:'r'+i}));
test('extract exact statements and preserve evidence',()=>{let r=parsed(SAMPLE);assert.equal(r.length,3);assert.equal(r[0].percent,80);assert.equal(r[1].child,'Willow Services Ltd');assert.ok(r[0].quote.includes('80%'));assert.ok(r[0].line>0);});
test('80% × 60% yields 48% along one path',()=>{assert.equal(ownershipPaths(parsed(SAMPLE),'Northstar Commerce PLC','Willow Services Ltd')[0].percent,48);});
test('conflicting claims block every affected path',()=>{let r=parsed(SAMPLE+'\nNorthstar Commerce PLC owns 75% of Harbor Payments Ltd.');assert.equal(conflicts(r).length,1);assert.equal(ownershipPaths(r,'Northstar Commerce PLC','Willow Services Ltd').length,0);});
test('excluding disputed evidence restores the path',()=>{let r=parsed(SAMPLE+'\nNorthstar Commerce PLC owns 75% of Harbor Payments Ltd.');r.at(-1).status='rejected';assert.equal(ownershipPaths(r,'Northstar Commerce PLC','Willow Services Ltd')[0].percent,48);});
test('invalid percentages and self ownership are rejected',()=>{let x=extractText('Alpha owns 101% of Beta.\nAlpha owns 0% of Beta.\nAlpha owns 50% of Alpha.','Alpha','d');assert.equal(x.relations.length,0);assert.equal(x.warnings.length,3);});
test('does not invent ownership from unstructured claims',()=>{assert.equal(parsed('Alpha may acquire Beta.\nAlpha does not own Beta.\nOwnership: unknown').length,0);});
test('subsidiary rows cannot support numeric ownership',()=>{let r=parsed('Subsidiaries\nName | Jurisdiction\nExample Ltd | Ireland');assert.equal(r.length,1);assert.equal(r[0].percent,null);assert.equal(ownershipPaths(r,'Northstar Commerce PLC','Example Ltd').length,0);});
test('cycles terminate without inventing extra paths',()=>{let r=parsed('Alpha owns 50% of Beta.\nBeta owns 50% of Alpha.\nBeta owns 40% of Gamma.');assert.equal(ownershipPaths(r,'Alpha','Gamma')[0].percent,20);});
test('separate paths are not summed',()=>{let r=parsed('Alpha owns 50% of Beta.\nAlpha owns 40% of Gamma.\nBeta owns 30% of Delta.\nGamma owns 20% of Delta.');assert.deepEqual(ownershipPaths(r,'Alpha','Delta').map(p=>p.percent),[15,8]);});
test('duplicate lines retain correct locations',()=>{let r=parsed('Alpha owns 50% of Beta.\nAlpha owns 50% of Beta.');assert.deepEqual(r.map(x=>x.line),[1,2]);});
test('ML ranks Linked In spelling variation above unrelated names',()=>{let m=matchEntities('Linked In Corporation',CASES[0].rows.map(r=>r[0]),model);assert.equal(m[0].name,'LinkedIn Corporation');assert.ok(m[0].score>m[1].score);});
test('empty matching request returns no results',()=>assert.deepEqual(matchEntities(' ',['Alpha'],model),[]));
test('numeric conflicts remain an explicit matching feature',()=>assert.equal(features('Cedar 10 Ltd','Cedar 11 Ltd')[5],1));
test('untrusted text is escaped in rendered evidence',()=>assert.equal(escapeHtml('<script>"x"&\'</script>'),'&lt;script&gt;&quot;x&quot;&amp;&#39;&lt;/script&gt;'));
test('public snapshots do not assert ownership percentages',()=>{assert.equal(CASES.length,2);assert.equal(CASES[0].rows.length,8);assert.equal(CASES[1].rows.length,3);for(const c of CASES)assert.ok(c.url.startsWith('https://www.sec.gov/Archives/'));});
